// <auto-generated />
using System;
using CodeMazeEFCore.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeMazeEFCore.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200124215503_AdditionsRowInserted")]
    partial class AdditionsRowInserted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeMazeEFCore.DataAccessLayer.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("IsRegularStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LocalCalculation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Student","Common");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("acd782c0-479a-4f51-8142-fa95e7d39dcc"),
                            Age = 30,
                            IsRegularStudent = false,
                            LocalCalculation = 0,
                            Name = "John Doe"
                        },
                        new
                        {
                            StudentId = new Guid("c8a1a32c-a936-4036-8a45-72fa1ac3048f"),
                            Age = 25,
                            IsRegularStudent = false,
                            LocalCalculation = 0,
                            Name = "Jane Doe"
                        },
                        new
                        {
                            StudentId = new Guid("1e399e6c-44d1-447d-ab4a-44df81eb0ef9"),
                            Age = 28,
                            IsRegularStudent = false,
                            LocalCalculation = 0,
                            Name = "Mike Miles"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
