// <auto-generated />
using System;
using CodeMazeEFCore.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeMazeEFCore.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeMazeEFCore.DataAccessLayer.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("IsRegularStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LocalCalculation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Student","Common");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("3c20a1fc-4b06-40af-8e6e-2c878b9525bb"),
                            Age = 30,
                            IsRegularStudent = false,
                            LocalCalculation = 0,
                            Name = "John Doe"
                        },
                        new
                        {
                            StudentId = new Guid("4a56e9a8-39bb-496a-91e4-bcaf05529c3f"),
                            Age = 25,
                            IsRegularStudent = false,
                            LocalCalculation = 0,
                            Name = "Jane Doe"
                        },
                        new
                        {
                            StudentId = new Guid("4a4369ae-c602-43ad-a53c-2c40dfd24e35"),
                            Age = 28,
                            IsRegularStudent = false,
                            LocalCalculation = 0,
                            Name = "Mike Miles"
                        },
                        new
                        {
                            StudentId = new Guid("6ef8d6dd-9514-4ee2-bcbd-20ba9d7eec48"),
                            Age = 100,
                            IsRegularStudent = false,
                            LocalCalculation = 0,
                            Name = "TEST Name"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
